services:
  - type: web
    name: lista-de-tarefas
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: local
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_LOG_LEVEL
        value: debug
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
      php artisan config:cache
      mkdir -p database
      touch database/database.sqlite
      php artisan migrate --force



